### ISSUE TITLE
why does this package depend on munin.zope

### ISSUE THREAD

**Issue by frisi** [IMIO/collective.monitor#2]
currently `munin.zope` is listed under install_requires and it's zcml is imported.

but it looks like no checks defined there are registered as probes.

did you plan to add probes from this package?

did you stop integrationg it for a specific reason (eg. technical problems)?

i'm especially interested in monitoring memory usage.
the `memory_percent` proble looks like it simply returns the percentage of totally available memory the instance is using.
the information returned by memory plugin of munin.zope is much more detailed

```
VmPeak.value 674996224.0
VmSize.value 622829568.0
VmLck.value 0.0
VmPin.value 0.0
VmHWM.value 183050240.0
VmRSS.value 182910976.0
VmData.value 457273344.0
VmStk.value 143360.0
VmExe.value 3268608.0
VmLib.value 11980800.0
VmPTE.value 704512.0
VmSwap.value 2035712.0
```

**Comment by bsuttor** [comment]
Hi,

I think it's because I started this package from Prodcuts.ZNagios and Prodcuts.ZNagios has graphs provided by zeo_munin.py

But indeed, I never implemented it and I have no plan to do that.

**Comment by frisi** [comment]
fine, thanks for your reply!

**Comment by hvelarde** [comment]
I think this package needs some code clean up; when I discovered five.z2monitor I looked on it but I found a lot of things that seemed to be just polluting it.
